package model;

import model.base.BaseDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dictionary extends BaseDictionary<Dictionary> {
	public static final Dictionary dao = new Dictionary().dao();
}
