package model;

import model.base.BaseFriendLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FriendLink extends BaseFriendLink<FriendLink> {
	public static final FriendLink dao = new FriendLink().dao();
}
