package model;

import model.base.BaseLinkDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LinkDictionary extends BaseLinkDictionary<LinkDictionary> {
	public static final LinkDictionary dao = new LinkDictionary().dao();
}
