package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLinkDictionary<M extends BaseLinkDictionary<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setLinkType(java.lang.String linkType) {
		set("linkType", linkType);
	}

	public java.lang.String getLinkType() {
		return get("linkType");
	}

	public void setDictionaryNo(java.lang.String dictionaryNo) {
		set("dictionaryNo", dictionaryNo);
	}

	public java.lang.String getDictionaryNo() {
		return get("dictionaryNo");
	}

	public void setLinkNo(java.lang.String linkNo) {
		set("linkNo", linkNo);
	}

	public java.lang.String getLinkNo() {
		return get("linkNo");
	}

}
